sudo: false
language: node_js
node_js:
  - '4.4'
before_install:
 - npm install -g bower
 - npm install -g gulp
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run startserver
  - sleep 1 # give server time to start
script:
  - npm run test-single-run --reporters=dots
  - node_modules/.bin/protractor protractor.conf.js --browser=firefox
deploy:
  provider: heroku
  app: fumblie-frontend
  on: master
  api_key:
    secure: "6dbf52d0-96e7-4ae2-a964-c1a31cdaffa8"
notifications:
  email: false
